../.././bkfdds ../../Benchmark/EPFL/adder.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/adder.blif -dumpblif > SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/arbiter.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/arbiter.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/bar.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/bar.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/cavlc.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/cavlc.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/ctrl.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/ctrl.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/dec.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/dec.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/i2c.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/i2c.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/int2float.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/int2float.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/mem_ctrl.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/mem_ctrl.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/priority.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/priority.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/router.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/router.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/sin.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/sin.blif -dumpblif >> SD_BKFDDgroupEPFLeasy_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/max.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 20 -choosedav 9700 -choosefail 80 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/max.blif -dumpblif > SD_BKFDDgroupEPFLhard_DFS.txt
../.././bkfdds ../../Benchmark/EPFL/voter.blif -ordering dfs -sdmode -autodyn -automethod bkfdd -davioexist 5 -choosenew 9800 -choosedav 9700 -choosefail 80 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/voter.blif -dumpblif >> SD_BKFDDgroupEPFLhard_DFS.txt
