.././nanotrav ../Benchmark/alu2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/alu2.blif > cuddverifyMCNC.txt
.././nanotrav ../Benchmark/alu4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/alu4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/amd.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/amd.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/apex1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/apex2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/apex3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/apex4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/apex5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/apex6.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex6.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/apex7.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex7.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/b2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/b2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/bc0.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/bc0.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/C1355.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C1355.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/C1908.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C1908.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/C2670.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C2670.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/C3540.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C3540.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/C432.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C432.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/C499.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C499.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/C5315.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C5315.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/C7552.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C7552.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/C880.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C880.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/chkn.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/chkn.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/cps.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/cps.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/dalu.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/dalu.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/des.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/des.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/dist.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/dist.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/duke2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/duke2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/e64.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/e64.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/ex4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ex4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/ex5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ex5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/example2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/example2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/frg2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/frg2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/gary.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/gary.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/i10.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i10.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/i2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/i3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/i4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/i5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/i6.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i6.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/i7.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i7.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/i8.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i8.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/i9.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i9.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/ibm.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ibm.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/in0.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in0.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/in1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/in2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/in3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/in4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/in5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/intb.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/intb.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/jbp.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/jbp.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/k2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/k2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/lin.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/lin.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/luc.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/luc.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/m2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/m2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/m3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/m3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/m4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/m4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/mainpla.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/mainpla.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/max1024.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/max1024.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/max128.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/max128.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/max512.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/max512.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/misex3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/misex3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/mlp4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/mlp4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/o64.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/o64.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/opa.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/opa.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/pair.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/pair.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/pope.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/pope.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/prom1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/prom1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/prom2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/prom2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/rd84.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/rd84.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/root.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/root.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/rot.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/rot.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/seq.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/seq.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/signet.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/signet.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/soar.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/soar.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/t1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/t1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/t481.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/t481.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/table3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/table3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/table5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/table5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/term1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/term1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/ti.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ti.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/too_large.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/too_large.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/ttt2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ttt2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/vda.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/vda.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/x1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/x3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/x4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/x6dn.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x6dn.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/x7dn.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x7dn.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/xparc.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/xparc.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/Z5xp1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/Z5xp1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/Z9sym.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/Z9sym.blif >> cuddverifyMCNC.txt
