.././nanotrav ../Benchmark/EPFL/adder.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/adder.blif > cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/arbiter.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/arbiter.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/bar.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/bar.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/cavlc.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/cavlc.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/ctrl.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/ctrl.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/dec.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/dec.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/i2c.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/i2c.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/int2float.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/int2float.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/mem_ctrl.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/mem_ctrl.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/priority.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/priority.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/router.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/router.blif >> cuddverifyEPFLeasy.txt
.././nanotrav ../Benchmark/EPFL/sin.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_EPFL/sin.blif >> cuddverifyEPFLeasy.txt
