.././nanotrav ../Benchmark/s1196.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s1196.blif > cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s1238.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s1238.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s13207.1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s13207.1.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s1423.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s1423.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s1488.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s1488.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s1494.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s1494.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s15850.1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s15850.1.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s208.1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s208.1.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s208.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s208.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s298.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s298.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s344.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s344.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s349.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s349.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s35932.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s35932.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s382.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s382.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s38417.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s38417.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s38584.1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s38584.1.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s386.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s386.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s400.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s400.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s420.1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s420.1.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s420.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s420.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s444.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s444.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s510.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s510.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s526.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s526.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s526n.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s526n.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s5378.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s5378.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s641.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s641.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s713.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s713.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s820.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s820.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s832.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s832.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s838.1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s838.1.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s838.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s838.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s9234.1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s9234.1.blif >> cuddverifyISCAS.txt
.././nanotrav ../Benchmark/s953.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_ISCAS/s953.blif >> cuddverifyISCAS.txt
