.././nanotrav ../Benchmark/MCNC/alu2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/alu2.blif > cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/alu4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/alu4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/amd.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/amd.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/apex1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/apex2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/apex3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/apex4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/apex5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/apex6.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex6.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/apex7.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/apex7.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/b2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/b2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/bc0.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/bc0.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/C1355.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C1355.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/C1908.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C1908.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/C2670.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C2670.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/C3540.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C3540.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/C432.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C432.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/C499.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C499.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/C5315.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C5315.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/C7552.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C7552.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/C880.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/C880.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/chkn.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/chkn.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/cps.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/cps.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/dalu.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/dalu.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/des.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/des.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/dist.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/dist.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/duke2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/duke2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/e64.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/e64.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/ex4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ex4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/ex5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ex5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/example2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/example2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/frg2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/frg2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/gary.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/gary.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/i10.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i10.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/i2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/i3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/i4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/i5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/i6.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i6.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/i7.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i7.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/i8.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i8.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/i9.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/i9.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/ibm.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ibm.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/in0.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in0.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/in1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/in2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/in3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/in4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/in5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/in5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/intb.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/intb.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/jbp.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/jbp.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/k2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/k2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/lin.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/lin.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/luc.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/luc.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/m2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/m2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/m3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/m3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/m4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/m4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/mainpla.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/mainpla.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/max1024.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/max1024.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/max128.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/max128.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/max512.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/max512.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/misex3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/misex3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/mlp4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/mlp4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/o64.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/o64.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/opa.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/opa.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/pair.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/pair.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/pope.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/pope.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/prom1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/prom1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/prom2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/prom2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/rd84.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/rd84.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/root.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/root.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/rot.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/rot.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/seq.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/seq.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/signet.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/signet.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/soar.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/soar.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/t1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/t1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/t481.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/t481.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/table3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/table3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/table5.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/table5.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/term1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/term1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/ti.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ti.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/too_large.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/too_large.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/ttt2.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/ttt2.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/vda.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/vda.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/x1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/x3.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x3.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/x4.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x4.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/x6dn.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x6dn.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/x7dn.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/x7dn.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/xparc.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/xparc.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/Z5xp1.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/Z5xp1.blif >> cuddverifyMCNC.txt
.././nanotrav ../Benchmark/MCNC/Z9sym.blif -autodyn -automethod group -reordering group -drop -verify benchmark_output_MCNC/Z9sym.blif >> cuddverifyMCNC.txt
