../.././bkfdds ../../Benchmark/EPFL/adder.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/adder.blif -dumpblif > SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/arbiter.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/arbiter.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/bar.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/bar.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/cavlc.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/cavlc.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/ctrl.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/ctrl.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/dec.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/dec.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/i2c.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/i2c.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/int2float.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/int2float.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/mem_ctrl.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/mem_ctrl.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/priority.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/priority.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/router.blif -sdmode -autodyn -automethod bkfdd -davioexist 50 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/router.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/sin.blif -sdmode -autodyn -automethod bkfdd -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/sin.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/max.blif -sdmode -autodyn -automethod bkfdd -choosenew 9996 -choosedav 9755 -choosefail 150 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/max.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/voter.blif -sdmode -autodyn -automethod bkfdd -davioexist 5 -choosenew 9900 -choosedav 9700 -choosefail 100 -reordering bkfdd -drop -dumpfile benchmark_output_BKFDD/voter.blif -dumpblif >> SD_BKFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/adder.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/adder.blif -dumpblif > SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/arbiter.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/arbiter.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/bar.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/bar.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/cavlc.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/cavlc.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/ctrl.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/ctrl.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/dec.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/dec.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/i2c.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/i2c.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/int2float.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/int2float.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/mem_ctrl.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/mem_ctrl.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/priority.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/priority.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/router.blif -sdmode -autodyn -automethod kfdd -davioexist 50 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/router.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/sin.blif -sdmode -autodyn -automethod kfdd -reordering kfdd -drop -dumpfile benchmark_output_KFDD/sin.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/max.blif -sdmode -autodyn -automethod kfdd -choosedav 9755 -choosefail 100 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/max.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
../.././bkfdds ../../Benchmark/EPFL/voter.blif -sdmode -autodyn -automethod kfdd -davioexist 5 -choosedav 9700 -choosefail 100 -reordering kfdd -drop -dumpfile benchmark_output_KFDD/voter.blif -dumpblif >> SD_KFDDgroupEPFLeasy.txt
